/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorNewUser;
import Controlador.ControladorCliente;
import Controlador.ControladorEntrenador;
import Controlador.ControladorGestionarClientes;
import Controlador.ControladorGestionarEntrenador;
import Controlador.ControladorGestionarInscripciones;
import Controlador.ControladorGestionarMembresias;
import Controlador.ControladorGestionarUsuarios;
import Controlador.ControladorInscripcion;
import Controlador.ControladorMembresia;
import Modelo.ClienteDAO;
import Modelo.EntrenadorDAO;
import Modelo.InscripcionDAO;
import Modelo.MembresiaDAO;
import Modelo.UsuarioDAO;

/**
 *
 * @author KARLARASLIN
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        mitemUsuarios = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuInscripciones = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuMembresías = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/vista.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(287, 70));

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/users.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ver.png"))); // NOI18N
        jMenuItem9.setText("Gestionar Usuarios");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuUsuarios.add(jMenuItem9);

        mitemUsuarios.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        mitemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/mas.png"))); // NOI18N
        mitemUsuarios.setText("Agregar Usuario");
        mitemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(mitemUsuarios);

        jMenuBar1.add(menuUsuarios);

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/clientes.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ver.png"))); // NOI18N
        jMenuItem10.setText("Gestionar Clientes");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuClientes.add(jMenuItem10);

        jMenuItem1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/mas.png"))); // NOI18N
        jMenuItem1.setText("Agregar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuClientes.add(jMenuItem1);

        jMenuBar1.add(menuClientes);

        menuInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/inscripcion.png"))); // NOI18N
        menuInscripciones.setText("Inscripciones");
        menuInscripciones.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ver.png"))); // NOI18N
        jMenuItem11.setText("Gestionar Inscripciones");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuInscripciones.add(jMenuItem11);

        jMenuItem2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/mas.png"))); // NOI18N
        jMenuItem2.setText("Añadir Inscripción");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuInscripciones.add(jMenuItem2);

        jMenuBar1.add(menuInscripciones);

        menuMembresías.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/membresia.png"))); // NOI18N
        menuMembresías.setText("Membresías");
        menuMembresías.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ver.png"))); // NOI18N
        jMenuItem12.setText("Gestionar Membresías ");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuMembresías.add(jMenuItem12);

        jMenuItem3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/mas.png"))); // NOI18N
        jMenuItem3.setText("Añadir Membresía");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuMembresías.add(jMenuItem3);

        jMenuBar1.add(menuMembresías);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/entrenador.png"))); // NOI18N
        jMenu1.setText("Entrenadores");
        jMenu1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/mas.png"))); // NOI18N
        jMenuItem7.setText("Añadir Entrenador");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ver.png"))); // NOI18N
        jMenuItem8.setText("Gestionar Entrenadores");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemUsuariosActionPerformed
        // TODO add your handling code here:
        NewUser ventanaUser= new NewUser();
        UsuarioDAO modelo= new UsuarioDAO();
        new ControladorNewUser(ventanaUser, modelo);
        ventanaUser.setLocation(100, 100);
        ventanaUser. setVisible(true);
    }//GEN-LAST:event_mitemUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        RegistroCliente nuevoCliente=new RegistroCliente();
        ClienteDAO modelo = new ClienteDAO();
        UsuarioDAO model = new UsuarioDAO();
        new ControladorCliente(nuevoCliente, modelo, model);
        nuevoCliente.setLocation(100, 100);
        nuevoCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        RegistroMembresia rMenmbresia=new RegistroMembresia();
        MembresiaDAO modelo=new MembresiaDAO();
        new ControladorMembresia(rMenmbresia,modelo);
        rMenmbresia.setLocation(100, 100);
        rMenmbresia.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        RegistroInscricpion nuevaIns=new RegistroInscricpion();
        InscripcionDAO modelo=new InscripcionDAO();
        ClienteDAO model = new ClienteDAO();
        MembresiaDAO mod = new MembresiaDAO();
        new ControladorInscripcion(nuevaIns, modelo, model, mod);
        nuevaIns.setLocation(100,100);
        nuevaIns.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        RegistroEntrenador nuevoEntrenador= new RegistroEntrenador();
        EntrenadorDAO modelo=new EntrenadorDAO();
        UsuarioDAO model = new UsuarioDAO();
        new ControladorEntrenador(nuevoEntrenador, modelo, model);
        nuevoEntrenador.setLocation(100, 100);
        nuevoEntrenador.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        GestionarUsuarios gestionarUsuarios=new GestionarUsuarios();
        gestionarUsuarios.setLocation(100,100);
        gestionarUsuarios.setVisible(true);
        UsuarioDAO user=new UsuarioDAO();
        new ControladorGestionarUsuarios(gestionarUsuarios, user);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        GestionarClientes vista= new GestionarClientes();
        vista.setLocation(100,100);
        vista.setVisible(true);
        ClienteDAO cliente=new ClienteDAO();
        new ControladorGestionarClientes(vista, cliente);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        GestionarMembresia vista=new GestionarMembresia();
        vista.setLocation(100,100);
        vista.setVisible(true);
        MembresiaDAO modelo=new MembresiaDAO();
        new ControladorGestionarMembresias(vista, modelo);
       
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        GestionarEntrenador vista=new GestionarEntrenador();
        vista.setLocation(100,100);
        vista.setVisible(true);
        EntrenadorDAO modelo=new EntrenadorDAO();
        new ControladorGestionarEntrenador(vista,modelo);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        GestionarInscripciones vista=new GestionarInscripciones();
        vista.setLocation(100,100);
        vista.setVisible(true);
        InscripcionDAO modelo=new InscripcionDAO();
        new ControladorGestionarInscripciones(vista, modelo);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuInscripciones;
    private javax.swing.JMenu menuMembresías;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenuItem mitemUsuarios;
    // End of variables declaration//GEN-END:variables
}
